spring:
  driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 2147483647
      properties:
        enable.idempotence: true
        request.timeout.ms: 5000
        delivery.timeout.ms: 60000
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: latest
      enable-auto-commit: false
    listener:
      missing-topics-fatal: false
      ack-mode: record
      retry:
        topic:
          attempts: 5
          delay: 2000

kafka:
  topic:
    properties:
      partitions: 1
      replication-factor: 1
orders:
  events:
    topic: orders-events
payments:
  events:
    topic: payments-events

jwt:
  secret: myVerySecretKeyNotLessThan32CharactersLong
  access-token-expiration: 3600000
  refresh-token-expiration: 604800000