server:
  servlet:
    context-path: ${SERVICES_COMMON_PATH}
  port: 8084

spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER_DOCKER}
    consumer:
      group-id: payments-service-group
      properties:
        spring.json.trusted.packages: "com.innowise.orderservice.*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.innowise.paymentservice.model.dto.kafka.OrderCreatedEvent
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo-1:27017,mongo-2:27017,mongo-3:27017/inno-payment-db?authSource=admin&replicaSet=rs0

external-api:
  url: "https://www.randomnumberapi.com/api/v1.0/random?min=1&max=100&count=1"