server:
  servlet:
    context-path: ${SERVICES_COMMON_PATH}
  port: 8083

spring:
  application:
    name: order-service
  config:
    activate:
      on-profile: default
    import:
      - configserver:http://localhost:8888
      - file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5435/inno-orders-db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER_LOCAL}
  cloud:
    openfeign:
      client:
        config:
          user-service:
            url: ${USER_SERVICE_LOCAL_URL}${SERVICES_COMMON_PATH}

resilience4j.circuitbreaker:
  instances:
    userService:
      sliding-window-size: 10
      failure-rate-threshold: 50
      wait-duration-in-open-state: 10s
      permitted-number-of-calls-in-half-open-state: 3
      automatic-transition-from-open-to-half-open-enabled: true

resilience4j.retry:
  instances:
    userService:
      max-attempts: 3
      wait-duration: 2s