server:
  servlet:
    context-path: ${SERVICES_COMMON_PATH}
  port: 8083

spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
  datasource:
    url: jdbc:postgresql://order-service-postgres:5432/inno-orders-db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER_DOCKER}
  cloud:
    openfeign:
      client:
        config:
          user-service:
            url: ${USER_SERVICE_DOCKER_URL}${SERVICES_COMMON_PATH}